# Create Datasets

- Use to split data signals into separate files.

In [1]:
import os
import sys

import pandas as pd

notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../signal'))

from data_processing import DataProcessing

## Load Data

In [2]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
data_path = os.path.join(base_data_path, 'WESAD/all_subjects/chest.csv')
df = DataProcessing.load_from_file(data_path, file_type='csv')
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df

,ACC_x,ACC_y,ACC_z,ECG,EMG,EDA,Temp,Resp,subject,label
0,0.9554,-0.2220,-0.5580,0.021423,-0.004440,5.250549,30.120758,-1.148987,S2,0
1,0.9258,-0.2216,-0.5538,0.020325,0.004349,5.267334,30.129517,-1.124573,S2,0
2,0.9082,-0.2196,-0.5392,0.016525,0.005173,5.243301,30.138214,-1.152039,S2,0
3,0.8974,-0.2102,-0.5122,0.016708,0.007187,5.249405,30.129517,-1.158142,S2,0
4,0.8882,-0.2036,-0.4824,0.011673,-0.015152,5.286407,30.130950,-1.161194,S2,0
...,...,...,...,...,...,...,...,...,...,...
60807595,0.9006,-0.0400,-0.1898,0.173676,-0.005539,7.265091,33.862762,0.318909,S17,0
60807596,0.9022,-0.0398,-0.1872,0.168777,-0.004944,7.266617,33.859740,0.233459,S17,0
60807597,0.9028,-0.0424,-0.1864,0.167130,-0.016068,7.262802,33.864290,0.318909,S17,0
60807598,0.9002,-0.0408,-0.1854,0.170334,0.005173,7.269669,33.862762,0.308228,S17,0
60807599,0.8996,-0.0414,-0.1862,0.175232,0.022751,7.268143,33.868835,0.274658,S17,0

## Signal to Save

In [9]:
df_to_save = df.loc[:, ['ECG', 'subject', 'label']]
df_to_save

               ECG subject  label
0         0.021423      S2      0
1         0.020325      S2      0
2         0.016525      S2      0
3         0.016708      S2      0
4         0.011673      S2      0
...            ...     ...    ...
60807595  0.173676     S17      0
60807596  0.168777     S17      0
60807597  0.167130     S17      0
60807598  0.170334     S17      0
60807599  0.175232     S17      0

[60807600 rows x 3 columns]

## Save Data

In [10]:
save_data_path = os.path.join(notebook_dir, "../../data/WESAD/all_subjects/")
save_data = os.path.join(save_data_path, 'ecg_chest.csv')
df_to_save.to_csv(save_data, index=False)