# Create Datasets

- Use to split data signals into separate files.

In [1]:
import os
import sys

import pandas as pd

notebook_dir = os.getcwd()

sys.path.append(os.path.join(notebook_dir, '../signal'))

from data_processing import DataProcessing

## Load Data

In [2]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
data_path = os.path.join(base_data_path, 'WESAD/all_subjects/chest.csv')
df = DataProcessing.load_from_file(data_path, file_type='csv')
df.drop(['Unnamed: 0'], axis=1, inplace=True)
df

,ACC_x,ACC_y,ACC_z,ECG,EMG,EDA,Temp,Resp,subject,label
0,0.9554,-0.2220,-0.5580,0.021423,-0.004440,5.250549,30.120758,-1.148987,S2,0
1,0.9258,-0.2216,-0.5538,0.020325,0.004349,5.267334,30.129517,-1.124573,S2,0
2,0.9082,-0.2196,-0.5392,0.016525,0.005173,5.243301,30.138214,-1.152039,S2,0
3,0.8974,-0.2102,-0.5122,0.016708,0.007187,5.249405,30.129517,-1.158142,S2,0
4,0.8882,-0.2036,-0.4824,0.011673,-0.015152,5.286407,30.130950,-1.161194,S2,0
...,...,...,...,...,...,...,...,...,...,...
60807595,0.9006,-0.0400,-0.1898,0.173676,-0.005539,7.265091,33.862762,0.318909,S17,0
60807596,0.9022,-0.0398,-0.1872,0.168777,-0.004944,7.266617,33.859740,0.233459,S17,0
60807597,0.9028,-0.0424,-0.1864,0.167130,-0.016068,7.262802,33.864290,0.318909,S17,0
60807598,0.9002,-0.0408,-0.1854,0.170334,0.005173,7.269669,33.862762,0.308228,S17,0
60807599,0.8996,-0.0414,-0.1862,0.175232,0.022751,7.268143,33.868835,0.274658,S17,0

In [3]:
copy_df = df.copy()
copy_df

,ACC_x,ACC_y,ACC_z,ECG,EMG,EDA,Temp,Resp,subject,label
0,0.9554,-0.2220,-0.5580,0.021423,-0.004440,5.250549,30.120758,-1.148987,S2,0
1,0.9258,-0.2216,-0.5538,0.020325,0.004349,5.267334,30.129517,-1.124573,S2,0
2,0.9082,-0.2196,-0.5392,0.016525,0.005173,5.243301,30.138214,-1.152039,S2,0
3,0.8974,-0.2102,-0.5122,0.016708,0.007187,5.249405,30.129517,-1.158142,S2,0
4,0.8882,-0.2036,-0.4824,0.011673,-0.015152,5.286407,30.130950,-1.161194,S2,0
...,...,...,...,...,...,...,...,...,...,...
60807595,0.9006,-0.0400,-0.1898,0.173676,-0.005539,7.265091,33.862762,0.318909,S17,0
60807596,0.9022,-0.0398,-0.1872,0.168777,-0.004944,7.266617,33.859740,0.233459,S17,0
60807597,0.9028,-0.0424,-0.1864,0.167130,-0.016068,7.262802,33.864290,0.318909,S17,0
60807598,0.9002,-0.0408,-0.1854,0.170334,0.005173,7.269669,33.862762,0.308228,S17,0
60807599,0.8996,-0.0414,-0.1862,0.175232,0.022751,7.268143,33.868835,0.274658,S17,0

## Keep Meaningful Labels

- 0 = not defined / transient
- 1 = baseline
- 2 = stress
- 3 = amusement
- 4 = meditation
- 5/6/7 = should be ignored in this dataset

In [4]:
filt_labels = copy_df['label'].isin([0, 5, 6, 7])
copy_df = copy_df[~filt_labels]
copy_df

,ACC_x,ACC_y,ACC_z,ECG,EMG,EDA,Temp,Resp,subject,label
214583,0.8914,-0.1102,-0.2576,0.030945,-0.003708,5.710983,29.083618,1.191711,S2,1
214584,0.8926,-0.1086,-0.2544,0.033646,-0.014145,5.719376,29.122437,1.139832,S2,1
214585,0.8930,-0.1094,-0.2580,0.033005,0.010208,5.706406,29.115234,1.141357,S2,1
214586,0.8934,-0.1082,-0.2538,0.031815,0.012634,5.712509,29.126709,1.155090,S2,1
214587,0.8930,-0.1096,-0.2570,0.030350,0.002060,5.727005,29.100860,1.133728,S2,1
...,...,...,...,...,...,...,...,...,...,...
60620859,0.4826,-0.0094,-0.8248,0.195236,0.013962,7.021713,34.080353,14.350891,S17,4
60620860,0.4838,-0.0088,-0.8298,0.178574,0.013504,7.020569,34.084900,14.419556,S17,4
60620861,0.4872,-0.0086,-0.8294,0.158020,0.024353,7.020569,34.022460,14.363098,S17,4
60620862,0.4858,-0.0080,-0.8376,0.129959,0.004623,7.029724,34.063538,14.361572,S17,4
60620863,0.4846,-0.0072,-0.8306,0.099289,-0.019318,7.025528,34.095550,14.436340,S17,4

## Signal of Interest

In [5]:
signal_df = copy_df.loc[:, ['ECG', 'subject', 'label']]
signal_df

               ECG subject  label
214583    0.030945      S2      1
214584    0.033646      S2      1
214585    0.033005      S2      1
214586    0.031815      S2      1
214587    0.030350      S2      1
...            ...     ...    ...
60620859  0.195236     S17      4
60620860  0.178574     S17      4
60620861  0.158020     S17      4
60620862  0.129959     S17      4
60620863  0.099289     S17      4

[31470603 rows x 3 columns]

## Clean Data

In [6]:
cleaned_signal_df = DataProcessing.get_cleaned_data(signal_df, 'ECG', 700)
cleaned_signal_df

               ECG subject  label  Cleaned ECG
214583    0.030945      S2      1     0.006982
214584    0.033646      S2      1     0.007554
214585    0.033005      S2      1     0.008133
214586    0.031815      S2      1     0.008776
214587    0.030350      S2      1     0.009535
...            ...     ...    ...          ...
60620859  0.195236     S17      4     0.270232
60620860  0.178574     S17      4     0.256066
60620861  0.158020     S17      4     0.241534
60620862  0.129959     S17      4     0.226662
60620863  0.099289     S17      4     0.211607

[31470603 rows x 4 columns]

## Set each subject with new row 0

In [7]:
new_signal_df = DataProcessing.reset_rows(cleaned_signal_df)
new_signal_df

              ECG subject  label  Cleaned ECG
0        0.030945      S2      1     0.006982
1        0.033646      S2      1     0.007554
2        0.033005      S2      1     0.008133
3        0.031815      S2      1     0.008776
4        0.030350      S2      1     0.009535
...           ...     ...    ...          ...
2104895  0.195236     S17      4     0.270232
2104896  0.178574     S17      4     0.256066
2104897  0.158020     S17      4     0.241534
2104898  0.129959     S17      4     0.226662
2104899  0.099289     S17      4     0.211607

[31470603 rows x 4 columns]

### Ex to get specific subject

In [35]:
s_df = DataProcessing.get_specific_subject_df(new_signal_df, 'S3')
s_df

              ECG subject  label  Cleaned ECG
0       -0.191849      S3      1    -0.176445
1       -0.186630      S3      1    -0.176682
2       -0.179260      S3      1    -0.176798
3       -0.171432      S3      1    -0.176842
4       -0.173264      S3      1    -0.176896
...           ...     ...    ...          ...
2054496  0.048477      S3      4     0.067996
2054497  0.035019      S3      4     0.065061
2054498  0.026917      S3      4     0.062005
2054499  0.019455      S3      4     0.058963
2054500  0.009888      S3      4     0.056059

[2054501 rows x 4 columns]

In [55]:
def check_order(s_df):
    # s is a Series here
    s = s_df.loc[s_df['label'].isin([3, 4]), 'label']

    # Group by runs where consecutive values are equal
    run_id = s.ne(s.shift()).cumsum()

    g = s.groupby(run_id)

    runs = pd.DataFrame({
        'label': g.first(),
        'start_idx': g.apply(lambda x: x.index[0]),
        'end_idx': g.apply(lambda x: x.index[-1]),
        'length': g.size()
    }).reset_index(drop=True)

    print(runs.head(10))

    run_starts = s[s.ne(s.shift())]
    run_order = run_starts.to_numpy()
    run_start_indices = run_starts.index.to_numpy()

    print(run_order[:20])
    print(run_start_indices[:20])

In [59]:
labels = new_signal_df['subject'].unique()
for label in labels:
    print(label)
    s_df = DataProcessing.get_specific_subject_df(new_signal_df, label)
    check_order(s_df)

S2
   label  start_idx  end_idx  length
0      4    1231300  1504998  273699
1      3    1504999  1758398  253400
2      4    1758399  2022298  263900
[4 3 4]
[1231300 1504999 1758399]
S3
   label  start_idx  end_idx  length
0      4    1246000  1527399  281400
1      3    1527400  1789899  262500
2      4    1789900  2054500  264601
[4 3 4]
[1246000 1527400 1789900]
S4
   label  start_idx  end_idx  length
0      3     810601  1071000  260400
1      4    1071001  2079000  563500
[3 4]
[ 810601 1071001]
S5
   label  start_idx  end_idx  length
0      3     838600  1100399  261800
1      4    1100400  2107699  555800
[3 4]
[ 838600 1100400]
S6
   label  start_idx  end_idx  length
0      4    1281000  1558899  277900
1      3    1558900  1819299  260400
2      4    1819300  2092299  273000
[4 3 4]
[1281000 1558900 1819300]
S7
   label  start_idx  end_idx  length
0      3     830200  1090600  260401
1      4    1090601  2091601  553001
[3 4]
[ 830200 1090601]
S8
   label  start_idx  end_idx  length
0      3     818300  1077298  258999
1      4    1077299  2103498  557200
[3 4]
[ 818300 1077299]
S9
   label  start_idx  end_idx  length
0      4    1277500  1556099  278600
1      3    1556100  1816499  260400
2      4    1816500  2092999  276500
[4 3 4]
[1277500 1556100 1816500]
S10
   label  start_idx  end_idx  length
0      3     826000  1086399  260400
1      4    1086400  2151099  557200
[3 4]
[ 826000 1086400]
S11
   label  start_idx  end_idx  length
0      4    1302000  1578500  276501
1      3    1578501  1836100  257600
2      4    1836101  2113300  277200
[4 3 4]
[1302000 1578501 1836101]
S13
   label  start_idx  end_idx  length
0      3     826001  1093400  267400
1      4    1093401  2114699  556499
[3 4]
[ 826001 1093401]
S14
   label  start_idx  end_idx  length
0      4    1298500  1576399  277900
1      3    1576400  1836800  260401
2      4    1836801  2114700  277900
[4 3 4]
[1298500 1576400 1836801]
S15
   label  start_idx  end_idx  length
0      3     822500  1082899  260400
1      4    1082900  2118898  555799
[3 4]
[ 822500 1082900]
S16
   label  start_idx  end_idx  length
0      4    1297101  1573599  276499
1      3    1573600  1831199  257600
2      4    1831200  2109099  277900
[4 3 4]
[1297101 1573600 1831200]
S17
   label  start_idx  end_idx  length
0      3     826700  1087099  260400
1      4    1087100  2104899  511700
[3 4]
[ 826700 1087100]

## Save Data

In [48]:
save_data_path = os.path.join(notebook_dir, "../../data/WESAD/all_subjects/")
save_data = os.path.join(save_data_path, 'ecg_chest-subset_labels-cleaned.csv')
new_signal_df.to_csv(save_data, index=True)

KeyboardInterrupt: