# Reproduce PulseLM Methods with WESAD Dataset

1. [PulseLM](https://github.com/manhph2211/PulseLM/)
2. [WESAD](https://archive.ics.uci.edu/dataset/465/wesad+wearable+stress+and+affect+detection)

In [1]:
import os
import sys
import glob

import numpy as np
import pandas as pd

# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../python/lamina/'))

# import log_files
import ppg
from data_processing import DataProcessing

## Load Data

- raw wrist BVP/PPG at 64 Hz via the Empatica E4

In [2]:
# def save_all_wrist_data_per_subject(notebook_dir: str):
#     base_dir = DataProcessing.load_base_data_path(notebook_dir)
#     pkl_files = sorted(glob.glob(os.path.join(base_dir, 'WESAD', 'per_subject', 'S*', 'S*.pkl')))

#     all_subject_dfs = []
    
#     for pkl_path in pkl_files:
#         with open(pkl_path, 'rb') as f:
#             data = pd.read_pickle(f)

#         subject = data['subject']
#         wrist = data['signal']['wrist']
#         label_700hz = data['label'].ravel()  # Chest-level 700 Hz ground-truth labels[cite: 1]

#         # Extract raw arrays for wrist channels
#         acc = wrist['ACC']           # 32 Hz[cite: 1]
#         bvp = wrist['BVP'].ravel()   # 64 Hz[cite: 1]
#         eda = wrist['EDA'].ravel()   # 4 Hz[cite: 1]
#         temp = wrist['TEMP'].ravel() # 4 Hz[cite: 1]

#         # Create separate DataFrames per channel
#         df_acc = pd.DataFrame({'ACC_x': acc[:, 0], 'ACC_y': acc[:, 1], 'ACC_z': acc[:, 2]})
#         df_bvp = pd.DataFrame({'BVP': bvp})
#         df_eda = pd.DataFrame({'EDA': eda})
#         df_temp = pd.DataFrame({'TEMP': temp})

#         # Concatenate wrist channels column-wise
#         subj_df = pd.concat([df_acc, df_bvp, df_eda, df_temp], axis=1)

#         # Downsample/align the 700 Hz labels to match wrist DataFrame length
#         label_indices = np.round(np.linspace(0, len(label_700hz) - 1, len(subj_df))).astype(int)
#         subj_df['label'] = label_700hz[label_indices]
#         subj_df['subject'] = subject

#         all_subject_dfs.append(subj_df)

#     # Combine all subject DataFrames
#     combined_df = pd.concat(all_subject_dfs, ignore_index=True)

#     # Save output CSV
#     out_path = os.path.join(base_dir, 'WESAD', 'all_subjects', 'wrist-all_labels.csv')
#     os.makedirs(os.path.dirname(out_path), exist_ok=True)
#     combined_df.to_csv(out_path, index=False)
    
#     # print(f"Saved wrist channels with preserved labels to: {out_path}")
#     return combined_df

In [3]:
# df = save_all_wrist_data_per_subject(notebook_dir)
# df

In [4]:
base_data_path = DataProcessing.load_base_data_path(notebook_dir)
data_path = os.path.join(base_data_path, 'WESAD/all_subjects/wrist-all_labels.csv')
df = DataProcessing.load_from_file(data_path, file_type='csv')
# df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [5]:
df.columns.to_list()

['ACC_x', 'ACC_y', 'ACC_z', 'BVP', 'EDA', 'TEMP', 'label', 'subject']

In [6]:
df = df.copy()
df

         ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
0        107.0 -105.0  127.0  10.17  0.349215  33.13      0     S10
1         67.0  -52.0   45.0  12.04  0.346656  33.16      0     S10
2         26.0   40.0    0.0  13.01  0.350494  33.16      0     S10
3         52.0   12.0   46.0  13.07  0.336423  33.16      0     S10
4         42.0   20.0   45.0  12.33  0.338981  33.16      0     S10
...        ...    ...    ...    ...       ...    ...    ...     ...
5559547    NaN    NaN    NaN  28.59       NaN    NaN      0      S9
5559548    NaN    NaN    NaN  29.45       NaN    NaN      0      S9
5559549    NaN    NaN    NaN  29.07       NaN    NaN      0      S9
5559550    NaN    NaN    NaN  27.74       NaN    NaN      0      S9
5559551    NaN    NaN    NaN  25.88       NaN    NaN      0      S9

[5559552 rows x 8 columns]

## Preprocessing

Label: ID of the respective study protocol condition
- 0 = not defined / transient
- 1 = baseline
- 2 = stress
- 3 = amusement
- 4 = meditation
- 5/6/7 = should be ignored in this dataset

### Get Subject of Interest + Health Metric of Interest

In [7]:
def get_per_subject(df):
    per_subject = {}
    entries = df['subject'].unique()
    for entry in entries:
        filt_subject = (df['subject'] == entry)
        subject_df = df[filt_subject]
        subject_df.reset_index(inplace=True)
        per_subject[entry] = subject_df
    return per_subject

In [8]:
per_subject_dfs = get_per_subject(df)
per_subject_dfs

{'S10':          index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0            0  107.0 -105.0  127.0  10.17  0.349215  33.13      0     S10
 1            1   67.0  -52.0   45.0  12.04  0.346656  33.16      0     S10
 2            2   26.0   40.0    0.0  13.01  0.350494  33.16      0     S10
 3            3   52.0   12.0   46.0  13.07  0.336423  33.16      0     S10
 4            4   42.0   20.0   45.0  12.33  0.338981  33.16      0     S10
 ...        ...    ...    ...    ...    ...       ...    ...    ...     ...
 351739  351739    NaN    NaN    NaN  28.01       NaN    NaN      0     S10
 351740  351740    NaN    NaN    NaN  44.41       NaN    NaN      0     S10
 351741  351741    NaN    NaN    NaN  57.59       NaN    NaN      0     S10
 351742  351742    NaN    NaN    NaN  65.93       NaN    NaN      0     S10
 351743  351743    NaN    NaN    NaN  69.86       NaN    NaN      0     S10

 [351744 rows x 9 columns],
 'S11':          index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       351744 -128.0  127.0  127.0 -12.14  4.445500  34.00      0     S11
 1       351745  -46.0    2.0   92.0  -6.20  4.911148  34.00      0     S11
 2       351746  -82.0  -34.0    5.0  -0.58  4.741007  34.00      0     S11
 3       351747 -105.0  -19.0   11.0   4.20  4.950804  34.00      0     S11
 4       351748  -72.0   -8.0   50.0   7.89  4.900373  34.03      0     S11
 ...        ...    ...    ...    ...    ...       ...    ...    ...     ...
 334907  686651    NaN    NaN    NaN   5.93       NaN    NaN      0     S11
 334908  686652    NaN    NaN    NaN   5.91       NaN    NaN      0     S11
 334909  686653    NaN    NaN    NaN   5.76       NaN    NaN      0     S11
 334910  686654    NaN    NaN    NaN   5.48       NaN    NaN      0     S11
 334911  686655    NaN    NaN    NaN   5.10       NaN    NaN      0     S11

 [334912 rows x 9 columns],
 'S13':           index  ACC_x  ACC_y  ACC_z     BVP       EDA   TEMP  label subject
 0        686656   54.0  -57.0  127.0   44.20  9.149161  34.71      0     S13
 1        686657   35.0   50.0   40.0   42.39  8.816556  34.71      0     S13
 2        686658    3.0   30.0   -2.0   40.48  8.713039  34.68      0     S13
 3        686659   38.0   23.0   73.0   39.05  8.687454  34.68      0     S13
 4        686660   12.0   24.0   74.0   38.29  8.746300  34.68      0     S13
 ...         ...    ...    ...    ...     ...       ...    ...    ...     ...
 354363  1041019    NaN    NaN    NaN -313.37       NaN    NaN      0     S13
 354364  1041020    NaN    NaN    NaN -328.45       NaN    NaN      0     S13
 354365  1041021    NaN    NaN    NaN -342.38       NaN    NaN      0     S13
 354366  1041022    NaN    NaN    NaN -352.82       NaN    NaN      0     S13
 354367  1041023    NaN    NaN    NaN -357.59       NaN    NaN      0     S13

 [354368 rows x 9 columns],
 'S14':           index  ACC_x  ACC_y  ACC_z     BVP       EDA   TEMP  label subject
 0       1041024  -23.0   31.0  127.0   -8.27  0.277864  31.97      0     S14
 1       1041025 -128.0  -31.0   62.0   -9.52  0.266351  31.97      0     S14
 2       1041026  -54.0  -58.0   26.0  -10.68  0.195992  31.97      0     S14
 3       1041027  -16.0  -37.0   39.0  -11.91  0.226694  31.95      0     S14
 4       1041028  -22.0  -38.0   35.0  -13.39  0.126912  31.95      0     S14
 ...         ...    ...    ...    ...     ...       ...    ...    ...     ...
 355067  1396091    NaN    NaN    NaN  -58.43       NaN    NaN      0     S14
 355068  1396092    NaN    NaN    NaN  -89.72       NaN    NaN      0     S14
 355069  1396093    NaN    NaN    NaN -123.97       NaN    NaN      0     S14
 355070  1396094    NaN    NaN    NaN -160.08       NaN    NaN      0     S14
 355071  1396095    NaN    NaN    NaN -195.94       NaN    NaN      0     S14

 [355072 rows x 9 columns],
 'S15':           index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       1396096   40.0  -45.0  127.0   1.35  0.220298  29.79      0     S15
 1       1396097  127.0   33.0   54.0   1.15  0.170407  29.79      0     S15
 2       1396098   38.0   30.0   17.0   1.13  0.189596  29.79      0     S15
 3       1396099   53.0   30.0   40.0   1.30  0.151218  29.83      0     S15
 4       1396100   36.0   39.0   34.0   1.66  0.166569  29.83      0     S15
 ...         ...    ...    ...    ...    ...       ...    ...    ...     ...
 336123  1732219    NaN    NaN    NaN  19.61       NaN    NaN      0     S15
 336124  1732220    NaN    NaN    NaN  20.17       NaN    NaN      0     S15
 336125  1732221    NaN    NaN    NaN  19.77       NaN    NaN      0     S15
 336126  1732222    NaN    NaN    NaN  18.51       NaN    NaN      0     S15
 336127  1732223    NaN    NaN    NaN  16.52       NaN    NaN      0     S15

 [336128 rows x 9 columns],
 'S16':           index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       1732224   86.0  -38.0  112.0  -1.60  0.254602  29.43      0     S16
 1       1732225  -40.0   26.0   -5.0  -2.09  0.253322  29.43      0     S16
 2       1732226   90.0   40.0    0.0  -2.72  0.250763  29.43      0     S16
 3       1732227   55.0   38.0   18.0  -3.31  0.246925  29.43      0     S16
 4       1732228   41.0   32.0   39.0  -3.74  0.243087  29.43      0     S16
 ...         ...    ...    ...    ...    ...       ...    ...    ...     ...
 360379  2092603    NaN    NaN    NaN  63.00       NaN    NaN      0     S16
 360380  2092604    NaN    NaN    NaN  82.79       NaN    NaN      0     S16
 360381  2092605    NaN    NaN    NaN  94.31       NaN    NaN      0     S16
 360382  2092606    NaN    NaN    NaN  94.96       NaN    NaN      0     S16
 360383  2092607    NaN    NaN    NaN  84.97       NaN    NaN      0     S16

 [360384 rows x 9 columns],
 'S17':           index  ACC_x  ACC_y  ACC_z   BVP       EDA   TEMP  label subject
 0       2092608  -36.0  -38.0 -128.0 -0.49  2.015176  33.39      0     S17
 1       2092609   -9.0   -9.0    2.0 -0.38  2.012617  33.37      0     S17
 2       2092610  113.0  -25.0   86.0 -0.36  2.001103  33.37      0     S17
 3       2092611 -115.0  -18.0  -35.0 -0.75  2.030529  33.37      0     S17
 4       2092612  -37.0  -24.0   56.0 -1.74  1.979353  33.37      0     S17
 ...         ...    ...    ...    ...   ...       ...    ...    ...     ...
 378875  2471483    NaN    NaN    NaN -2.09       NaN    NaN      0     S17
 378876  2471484    NaN    NaN    NaN -3.28       NaN    NaN      0     S17
 378877  2471485    NaN    NaN    NaN -4.43       NaN    NaN      0     S17
 378878  2471486    NaN    NaN    NaN -5.44       NaN    NaN      0     S17
 378879  2471487    NaN    NaN    NaN -6.21       NaN    NaN      0     S17

 [378880 rows x 9 columns],
 'S2':           index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       2471488   62.0  -21.0  107.0 -59.37  1.138257  35.41      0      S2
 1       2471489   66.0   13.0   53.0 -53.42  1.125444  35.41      0      S2
 2       2471490   41.0    9.0   15.0 -44.40  1.011405  35.41      0      S2
 3       2471491   52.0   16.0   24.0 -33.17  1.033188  35.41      0      S2
 4       2471492   54.0   15.0   34.0 -20.79  0.935807  35.41      0      S2
 ...         ...    ...    ...    ...    ...       ...    ...    ...     ...
 389051  2860539    NaN    NaN    NaN  18.33       NaN    NaN      0      S2
 389052  2860540    NaN    NaN    NaN  18.26       NaN    NaN      0      S2
 389053  2860541    NaN    NaN    NaN  18.26       NaN    NaN      0      S2
 389054  2860542    NaN    NaN    NaN  18.68       NaN    NaN      0      S2
 389055  2860543    NaN    NaN    NaN  19.71       NaN    NaN      0      S2

 [389056 rows x 9 columns],
 'S3':           index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       2860544 -128.0  127.0  127.0  16.49  2.248749  31.73      0      S3
 1       2860545  -41.0   49.0   76.0  15.80  2.710001  31.73      0      S3
 2       2860546   -3.0   14.0   14.0  14.58  2.554969  31.73      0      S3
 3       2860547  -79.0  -34.0  -10.0  13.02  2.818907  31.73      0      S3
 4       2860548 -104.0  -12.0   67.0  11.38  2.630563  31.73      0      S3
 ...         ...    ...    ...    ...    ...       ...    ...    ...     ...
 415547  3276091    NaN    NaN    NaN   5.44       NaN    NaN      0      S3
 415548  3276092    NaN    NaN    NaN   5.20       NaN    NaN      0      S3
 415549  3276093    NaN    NaN    NaN   4.98       NaN    NaN      0      S3
 415550  3276094    NaN    NaN    NaN   4.74       NaN    NaN      0      S3
 415551  3276095    NaN    NaN    NaN   4.44       NaN    NaN      0      S3

 [415552 rows x 9 columns],
 'S4':           index  ACC_x  ACC_y  ACC_z     BVP       EDA   TEMP  label subject
 0       3276096 -128.0  122.0   88.0   -3.69  0.169117  32.53      0      S4
 1       3276097  -31.0  -34.0   77.0   -5.53  0.164001  32.53      0      S4
 2       3276098  -61.0    4.0   62.0   -7.82  0.167838  32.53      0      S4
 3       3276099  -47.0   -5.0   67.0  -10.45  0.155047  32.53      0      S4
 4       3276100  -19.0   -2.0   84.0  -13.32  0.158884  32.53      0      S4
 ...         ...    ...    ...    ...     ...       ...    ...    ...     ...
 411067  3687163    NaN    NaN    NaN  -94.58       NaN    NaN      0      S4
 411068  3687164    NaN    NaN    NaN  -99.07       NaN    NaN      0      S4
 411069  3687165    NaN    NaN    NaN -102.58       NaN    NaN      0      S4
 411070  3687166    NaN    NaN    NaN -105.06       NaN    NaN      0      S4
 411071  3687167    NaN    NaN    NaN -106.60       NaN    NaN      0      S4

 [411072 rows x 9 columns],
 'S5':           index  ACC_x  ACC_y  ACC_z   BVP       EDA   TEMP  label subject
 0       3687168  -16.0  -45.0  127.0 -7.25  0.547723  34.09      0      S5
 1       3687169   69.0    9.0  127.0 -8.57  0.481218  34.09      0      S5
 2       3687170   45.0   35.0  -12.0 -9.48  0.518239  34.09      0      S5
 3       3687171   37.0   38.0   36.0 -9.93  0.440223  34.11      0      S5
 4       3687172   27.0   38.0   37.0 -9.79  0.391623  34.11      0      S5
 ...         ...    ...    ...    ...   ...       ...    ...    ...     ...
 400507  4087675    NaN    NaN    NaN  0.46       NaN    NaN      0      S5
 400508  4087676    NaN    NaN    NaN -1.46       NaN    NaN      0      S5
 400509  4087677    NaN    NaN    NaN -4.13       NaN    NaN      0      S5
 400510  4087678    NaN    NaN    NaN -7.07       NaN    NaN      0      S5
 400511  4087679    NaN    NaN    NaN -9.88       NaN    NaN      0      S5

 [400512 rows x 9 columns],
 'S6':           index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       4087680  112.0  -19.0  127.0   4.26  2.779563  30.03      0      S6
 1       4087681   44.0   18.0   10.0   3.12  2.785958  30.03      0      S6
 2       4087682   52.0   16.0   30.0   1.70  2.761658  30.03      0      S6
 3       4087683   62.0   31.0   32.0  -0.03  2.729684  30.03      0      S6
 4       4087684   53.0   40.0   22.0  -1.92  2.693874  30.03      0      S6
 ...         ...    ...    ...    ...    ...       ...    ...    ...     ...
 452539  4540219    NaN    NaN    NaN -23.73       NaN    NaN      0      S6
 452540  4540220    NaN    NaN    NaN -32.57       NaN    NaN      0      S6
 452541  4540221    NaN    NaN    NaN -40.67       NaN    NaN      0      S6
 452542  4540222    NaN    NaN    NaN -47.72       NaN    NaN      0      S6
 452543  4540223    NaN    NaN    NaN -53.59       NaN    NaN      0      S6

 [452544 rows x 9 columns],
 'S7':           index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       4540224  127.0  -50.0  127.0   9.57  5.969716  33.25      0      S7
 1       4540225  127.0   46.0   -8.0   7.41  6.100200  33.25      0      S7
 2       4540226   90.0   24.0   57.0   5.11  6.096362  33.25      0      S7
 3       4540227   40.0   19.0   92.0   2.84  6.088686  33.25      0      S7
 4       4540228   19.0    5.0   68.0   0.72  6.114272  33.31      0      S7
 ...         ...    ...    ...    ...    ...       ...    ...    ...     ...
 335227  4875451    NaN    NaN    NaN -29.93       NaN    NaN      0      S7
 335228  4875452    NaN    NaN    NaN -29.80       NaN    NaN      0      S7
 335229  4875453    NaN    NaN    NaN -29.52       NaN    NaN      0      S7
 335230  4875454    NaN    NaN    NaN -28.97       NaN    NaN      0      S7
 335231  4875455    NaN    NaN    NaN -28.04       NaN    NaN      0      S7

 [335232 rows x 9 columns],
 'S8':           index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       4875456   -7.0  -15.0  -34.0  -3.27  0.503081  33.25      0      S8
 1       4875457  -38.0  127.0  127.0   6.25  0.515874  33.25      0      S8
 2       4875458  127.0  -48.0  127.0  13.86  0.799868  33.29      0      S8
 3       4875459   58.0  -15.0   60.0  19.77  0.858713  33.29      0      S8
 4       4875460   42.0  -19.0   64.0  24.30  0.657871  33.29      0      S8
 ...         ...    ...    ...    ...    ...       ...    ...    ...     ...
 349819  5225275    NaN    NaN    NaN   6.81       NaN    NaN      0      S8
 349820  5225276    NaN    NaN    NaN   5.74       NaN    NaN      0      S8
 349821  5225277    NaN    NaN    NaN   4.59       NaN    NaN      0      S8
 349822  5225278    NaN    NaN    NaN   3.35       NaN    NaN      0      S8
 349823  5225279    NaN    NaN    NaN   1.99       NaN    NaN      0      S8

 [349824 rows x 9 columns],
 'S9':           index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
 0       5225280 -128.0  -55.0  127.0 -10.02  0.329014  33.87      0      S9
 1       5225281 -128.0   -3.0   85.0  -7.43  0.326456  33.87      0      S9
 2       5225282   30.0   75.0   56.0  -4.57  0.336689  33.87      0      S9
 3       5225283   22.0   41.0   54.0  -1.87  0.332852  33.87      0      S9
 4       5225284  -23.0   34.0   46.0   0.39  0.327735  33.87      0      S9
 ...         ...    ...    ...    ...    ...       ...    ...    ...     ...
 334267  5559547    NaN    NaN    NaN  28.59       NaN    NaN      0      S9
 334268  5559548    NaN    NaN    NaN  29.45       NaN    NaN      0      S9
 334269  5559549    NaN    NaN    NaN  29.07       NaN    NaN      0      S9
 334270  5559550    NaN    NaN    NaN  27.74       NaN    NaN      0      S9
 334271  5559551    NaN    NaN    NaN  25.88       NaN    NaN      0      S9

 [334272 rows x 9 columns]}

In [9]:
s_df = per_subject_dfs['S7']
s_df

          index  ACC_x  ACC_y  ACC_z    BVP       EDA   TEMP  label subject
0       4540224  127.0  -50.0  127.0   9.57  5.969716  33.25      0      S7
1       4540225  127.0   46.0   -8.0   7.41  6.100200  33.25      0      S7
2       4540226   90.0   24.0   57.0   5.11  6.096362  33.25      0      S7
3       4540227   40.0   19.0   92.0   2.84  6.088686  33.25      0      S7
4       4540228   19.0    5.0   68.0   0.72  6.114272  33.31      0      S7
...         ...    ...    ...    ...    ...       ...    ...    ...     ...
335227  4875451    NaN    NaN    NaN -29.93       NaN    NaN      0      S7
335228  4875452    NaN    NaN    NaN -29.80       NaN    NaN      0      S7
335229  4875453    NaN    NaN    NaN -29.52       NaN    NaN      0      S7
335230  4875454    NaN    NaN    NaN -28.97       NaN    NaN      0      S7
335231  4875455    NaN    NaN    NaN -28.04       NaN    NaN      0      S7

[335232 rows x 9 columns]

In [10]:
s_df['label'].value_counts()

label
0    134591
1     75904
4     50560
2     40960
3     23808
7      3393
5      3200
6      2816
Name: count, dtype: int64

In [11]:
s_df = per_subject_dfs['S7']
s_metric_df = s_df.loc[:, ['BVP', 'label']]
s_metric_df

          BVP  label
0        9.57      0
1        7.41      0
2        5.11      0
3        2.84      0
4        0.72      0
...       ...    ...
335227 -29.93      0
335228 -29.80      0
335229 -29.52      0
335230 -28.97      0
335231 -28.04      0

[335232 rows x 2 columns]

### Separate Contiguous Protocol Runs & Generate Reset Time Components

In [12]:
run_id = (s_metric_df['label'] != s_metric_df['label'].shift()).cumsum()

# Build continuous run DataFrames with reset time
run_dfs = []
for (lbl, run), group_df in s_metric_df.groupby(['label', run_id]):
    group_df = group_df.reset_index(drop=True)
    group_df = DataProcessing.create_time_df(group_df, sampling_rate=64)
    group_df['run_id'] = run
    run_dfs.append(group_df)

s_raw_runs_df = pd.concat(run_dfs, ignore_index=True)
s_raw_runs_df

         BVP  label  Milliseconds   Seconds                   Time  run_id
0       9.57      0          0.00   0.00000        0 days 00:00:00       1
1       7.41      0         15.62   0.01562 0 days 00:00:00.020000       1
2       5.11      0         31.25   0.03125 0 days 00:00:00.030000       1
3       2.84      0         46.88   0.04688 0 days 00:00:00.050000       1
4       0.72      0         62.50   0.06250 0 days 00:00:00.060000       1
...      ...    ...           ...       ...                    ...     ...
335227  7.28      7      52937.50  52.93750 0 days 00:00:52.940000       8
335228  6.84      7      52953.12  52.95312 0 days 00:00:52.950000       8
335229  6.39      7      52968.75  52.96875 0 days 00:00:52.970000       8
335230  6.01      7      52984.38  52.98438 0 days 00:00:52.980000       8
335231  5.69      7      53000.00  53.00000        0 days 00:00:53       8

[335232 rows x 6 columns]

## Reproducibility Steps

1. Resample to 125 Hz
2. Fourth-order Butterworth low-pass filter at 8 Hz
3. DC offset removal
4. Slice into 10-second windows
5. Per-segment min-max normalization

#### 1. Resample to 125 Hz

#### 2. Fourth-order Butterworth low-pass filter at 8 Hz

#### 3. DC offset removal

#### 4. Slice into 10-second windows

#### 5. Per-segment min-max normalization